@user = User.create(:email => 'admin@example.com', :password => 'admin123#')
@role = Role.create(:name => 'admin')
Permission.create(:user_id => @user.id, :role_id => @role.id)
StoreSetting.create(:user_id => @user.id)
Category.create(name: 'Category #1', description: 'This is your first category.', visible: true, sorting: 1000)
AttributeType.create(name: 'Weight', measurement: 'g')
@country = Country.create(name: 'United Kingdom', language: 'English', iso: 'EN')
@zone = Zone.create(name: 'EU', country_ids: [@country.id])
@shipping = Shipping.create(name: 'Royal Mail 1st class', price: '5.67', description: 'Standard Royal Mail delivery service within 1-2 business days.', zone_ids: [@zone.id])
Tier.create(length_start: '0', length_end: '100', weight_start: '0', weight_end: '50', thickness_start: '0', thickness_end: '100', shipping_ids: [@shipping.id])
